export const GameKeys = {
    JOINED_GAME: "JOINED_GAME",
    PLAYER_JOINED: "PLAYER_JOINED",
    PLAYER_LEFT: "PLAYER_LEFT",
    GAME_STARTED: "GAME_STARTED",
    PLAYER_RECIEVED_CARD: "PLAYER_RECIEVED_CARD"
}
