export const GameKeys = {
    JOINED_GAME: "JOINED_GAME",
    PLAYER_JOINED: "PLAYER_JOINED",
    PLAYER_LEFT: "PLAYER_LEFT",
    GAME_STARTED: "GAME_STARTED",
    PLAYER_RECIEVED_CARD: "PLAYER_RECIEVED_CARD",
    GAME_DEALT_BLACK_CARD: "GAME_DEALT_BLACK_CARD",
    PLAYER_CHOSE_CARDS: "PLAYER_CHOSE_CARDS",
    ROUND_STATUS_CHANGED: "ROUND_STATUS_CHANGED"
}
